/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useKeyboardControls } from "@react-three/drei";

export function Player(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./Soldier.glb");
  console.log(animations);
  const { actions } = useAnimations(animations, group);

  const [subscribeKeys, getKeys] = useKeyboardControls();

  useEffect(() => {
    actions.Idle.reset().fadeIn(0.5).play();
    const unsubcribeJump = subscribeKeys(
      (state) => state.jump,
      (pressed) => {
        console.log("jump", pressed);
      },
    );
    const unsubcribeForward = subscribeKeys(
      (state) => state.forward,
      (pressed) => {
        console.log("forward", pressed);
        actions.Run.reset().fadeIn(0.5).play();
      },
    );
    const unsubcribeBack = subscribeKeys(
      (state) => state.back,
      (pressed) => {
        console.log("back", pressed);
        actions.Walk.reset().fadeIn(0.5).play();
      },
    );
    const unsubcribeLeft = subscribeKeys(
      (state) => state.left,
      (pressed) => {
        console.log("left", pressed);
        actions.Idle.reset().fadeIn(0.5).play();
      },
    );
    const unsubcribeRight = subscribeKeys(
      (state) => state.right,
      (pressed) => {
        console.log("right", pressed);
        actions.Run.reset().fadeIn(0.5).play();
      },
    );
    const unsubcribeShift = subscribeKeys(
      (state) => state.run,
      (pressed) => {
        console.log("shift", pressed);
      },
    );
    return () => {
      unsubcribeJump();
      unsubcribeForward();
      unsubcribeBack();
      unsubcribeLeft();
      unsubcribeRight();
      unsubcribeShift();
    };
  }, []);

  // useEffect(() => {
  //   actions.Run.reset().fadeIn(0.5).play();
  //   return () => {
  //     // action.fadeOut(0.5)
  //   };
  // }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        userData={{
          background_color: [
            0.05087608844041824, 0.05087608844041824, 0.05087608844041824,
          ],
          frames_per_second: 30,
        }}
      >
        <group
          name="Character"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.01}
          userData={{ name: "Character" }}
        >
          <skinnedMesh
            name="vanguard_Mesh"
            geometry={nodes.vanguard_Mesh.geometry}
            material={materials.VanguardBodyMat}
            skeleton={nodes.vanguard_Mesh.skeleton}
            userData={{ name: "vanguard_Mesh" }}
          />
          <skinnedMesh
            name="vanguard_visor"
            geometry={nodes.vanguard_visor.geometry}
            material={materials.Vanguard_VisorMat}
            skeleton={nodes.vanguard_visor.skeleton}
            userData={{ name: "vanguard_visor" }}
          />
          <primitive object={nodes.mixamorigHips} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Soldier.glb");
